insert into petshop (name, age, kind) values ('Wendye', 47, 'Galapagos sea lion');
insert into petshop (name, age, kind) values ('Mariquilla', 3, 'Lesser flamingo');
insert into petshop (name, age, kind) values ('Hildagard', 60, 'Turaco, violet-crested');
insert into petshop (name, age, kind) values ('Cherlyn', 92, 'Duck, white-faced whistling');
insert into petshop (name, age, kind) values ('Verne', 4, 'Zorro, azara''s');
insert into petshop (name, age, kind) values ('Adriano', 93, 'European stork');
insert into petshop (name, age, kind) values ('Sampson', 11, 'Sloth bear');
insert into petshop (name, age, kind) values ('Stephen', 50, 'Numbat');
insert into petshop (name, age, kind) values ('Taddeo', 40, 'Western palm tanager (unidentified)');
insert into petshop (name, age, kind) values ('Morgan', 67, 'Savannah deer (unidentified)');
insert into petshop (name, age, kind) values ('Wilek', 7, 'Stilt, black-winged');
insert into petshop (name, age, kind) values ('Elaina', 36, 'Cook''s tree boa');
insert into petshop (name, age, kind) values ('Noelani', 43, 'Crane, wattled');
insert into petshop (name, age, kind) values ('Else', 81, 'Two-toed sloth');
insert into petshop (name, age, kind) values ('Tiffany', 19, 'Cockatoo, red-breasted');
insert into petshop (name, age, kind) values ('Ninnetta', 7, 'Darter, african');
insert into petshop (name, age, kind) values ('Lonee', 26, 'Dragonfly, russian');
insert into petshop (name, age, kind) values ('Pearline', 33, 'Crow, american');
insert into petshop (name, age, kind) values ('Tibold', 4, 'Verreaux''s sifaka');
insert into petshop (name, age, kind) values ('Oran', 82, 'Southern tamandua');
insert into petshop (name, age, kind) values ('Stan', 16, 'Pigeon, feral rock');
insert into petshop (name, age, kind) values ('Flory', 22, 'Hornbill, leadbeateri''s ground');
insert into petshop (name, age, kind) values ('Noak', 21, 'Pale-throated three-toed sloth');
insert into petshop (name, age, kind) values ('Herschel', 38, 'Collared peccary');
insert into petshop (name, age, kind) values ('Karlyn', 77, 'Zebra, plains');
insert into petshop (name, age, kind) values ('Janek', 83, 'Buffalo, american');
insert into petshop (name, age, kind) values ('Stacee', 17, 'Turtle (unidentified)');
insert into petshop (name, age, kind) values ('Mozelle', 82, 'Giant girdled lizard');
insert into petshop (name, age, kind) values ('Burch', 29, 'Red-breasted nuthatch');
insert into petshop (name, age, kind) values ('Jeffry', 8, 'Bateleur eagle');
insert into petshop (name, age, kind) values ('Kiley', 20, 'Dove, laughing');
insert into petshop (name, age, kind) values ('Bethany', 82, 'Owl, burrowing');
insert into petshop (name, age, kind) values ('Jerad', 38, 'African pied wagtail');
insert into petshop (name, age, kind) values ('Kathryne', 25, 'Great white pelican');
insert into petshop (name, age, kind) values ('Kaia', 93, 'Violet-eared waxbill');
insert into petshop (name, age, kind) values ('Krishna', 72, 'Bee-eater, white-fronted');
insert into petshop (name, age, kind) values ('Julia', 46, 'Common pheasant');
insert into petshop (name, age, kind) values ('Marcelia', 81, 'Cat, tiger');
insert into petshop (name, age, kind) values ('Esmeralda', 6, 'Mynah, common');
insert into petshop (name, age, kind) values ('Malina', 18, 'Puna ibis');
insert into petshop (name, age, kind) values ('Lucia', 57, 'Southern tamandua');
insert into petshop (name, age, kind) values ('Gabbie', 8, 'Black-tailed prairie dog');
insert into petshop (name, age, kind) values ('Christoper', 77, 'Cockatoo, long-billed');
insert into petshop (name, age, kind) values ('Brandtr', 62, 'Weaver, sociable');
insert into petshop (name, age, kind) values ('Jessie', 76, 'Owl, australian masked');
insert into petshop (name, age, kind) values ('Marianna', 27, 'Gull, dusky');
insert into petshop (name, age, kind) values ('Valery', 18, 'Weaver, lesser masked');
insert into petshop (name, age, kind) values ('Bruis', 83, 'Brown lemur');
insert into petshop (name, age, kind) values ('Gerry', 29, 'Jungle kangaroo');
insert into petshop (name, age, kind) values ('Inglis', 42, 'Antelope ground squirrel');
insert into petshop (name, age, kind) values ('Hester', 13, 'Hawk, galapagos');
insert into petshop (name, age, kind) values ('Debbi', 17, 'Neotropic cormorant');
insert into petshop (name, age, kind) values ('Ebba', 67, 'Red-billed tropic bird');
insert into petshop (name, age, kind) values ('Sayres', 79, 'Cormorant, javanese');
insert into petshop (name, age, kind) values ('Yevette', 15, 'Lion, southern sea');
insert into petshop (name, age, kind) values ('Deane', 79, 'Marabou stork');
insert into petshop (name, age, kind) values ('Bernhard', 23, 'Peacock, blue');
insert into petshop (name, age, kind) values ('Connie', 32, 'Tenrec, tailless');
insert into petshop (name, age, kind) values ('Tom', 38, 'Rat, desert kangaroo');
insert into petshop (name, age, kind) values ('Jaime', 54, 'Greater rhea');
insert into petshop (name, age, kind) values ('Stillmann', 4, 'Possum, golden brush-tailed');
insert into petshop (name, age, kind) values ('Cornell', 86, 'Asian red fox');
insert into petshop (name, age, kind) values ('Melonie', 94, 'Dove, white-winged');
insert into petshop (name, age, kind) values ('Maisie', 7, 'Jackrabbit, white-tailed');
insert into petshop (name, age, kind) values ('Joye', 50, 'Black-capped capuchin');
insert into petshop (name, age, kind) values ('Eldon', 18, 'Ocelot');
insert into petshop (name, age, kind) values ('Rockey', 2, 'Red-tailed cockatoo');
insert into petshop (name, age, kind) values ('Vera', 48, 'Kingfisher, pied');
insert into petshop (name, age, kind) values ('Jobey', 43, 'Arctic fox');
insert into petshop (name, age, kind) values ('Chantalle', 73, 'Bird, red-billed tropic');
insert into petshop (name, age, kind) values ('Jennifer', 50, 'Savannah deer');
insert into petshop (name, age, kind) values ('Alfonse', 33, 'Gull, kelp');
insert into petshop (name, age, kind) values ('Margarethe', 52, 'Plains zebra');
insert into petshop (name, age, kind) values ('Eberto', 35, 'Constrictor, eastern boa');
insert into petshop (name, age, kind) values ('Shel', 34, 'Snowy owl');
insert into petshop (name, age, kind) values ('Jeth', 64, 'Slender loris');
insert into petshop (name, age, kind) values ('Lance', 44, 'Fox, grey');
insert into petshop (name, age, kind) values ('Tallou', 39, 'Mountain lion');
insert into petshop (name, age, kind) values ('Reynolds', 85, 'Red-billed toucan');
insert into petshop (name, age, kind) values ('Sigismund', 28, 'Rattlesnake, horned');
insert into petshop (name, age, kind) values ('Bibi', 16, 'Swan, trumpeter');
insert into petshop (name, age, kind) values ('Farrel', 75, 'Rhea, common');
insert into petshop (name, age, kind) values ('Tarrah', 73, 'Pigeon, feral rock');
insert into petshop (name, age, kind) values ('Terence', 19, 'Tern, royal');
insert into petshop (name, age, kind) values ('Olivette', 13, 'Common raccoon');
insert into petshop (name, age, kind) values ('Claiborn', 74, 'Common langur');
insert into petshop (name, age, kind) values ('Lorrie', 55, 'Sheep, stone');
insert into petshop (name, age, kind) values ('Amabelle', 78, 'Blue racer');
insert into petshop (name, age, kind) values ('Tedda', 32, 'Otter, african clawless');
insert into petshop (name, age, kind) values ('Willyt', 9, 'Asian lion');
insert into petshop (name, age, kind) values ('Kinna', 8, 'Jaguar');
insert into petshop (name, age, kind) values ('Cyb', 66, 'Southern tamandua');
insert into petshop (name, age, kind) values ('Yovonnda', 9, 'Campo flicker');
insert into petshop (name, age, kind) values ('Bancroft', 60, 'Prairie falcon');
insert into petshop (name, age, kind) values ('Cathi', 15, 'Grant''s gazelle');
insert into petshop (name, age, kind) values ('Torrie', 18, 'Galapagos dove');
insert into petshop (name, age, kind) values ('Persis', 97, 'Zorilla');
insert into petshop (name, age, kind) values ('Clemmy', 72, 'Dusky gull');
insert into petshop (name, age, kind) values ('Kermy', 8, 'Mouse, four-striped grass');
insert into petshop (name, age, kind) values ('Emelia', 71, 'Eagle, african fish');
insert into petshop (name, age, kind) values ('Kermit', 93, 'Seal, northern fur');
insert into petshop (name, age, kind) values ('Giovanni', 59, 'Hoffman''s sloth');
insert into petshop (name, age, kind) values ('Ches', 20, 'Crown of thorns starfish');
insert into petshop (name, age, kind) values ('Katheryn', 90, 'Chameleon (unidentified)');
insert into petshop (name, age, kind) values ('Isabelle', 96, 'Guerza');
insert into petshop (name, age, kind) values ('Elie', 81, 'Goldeneye, barrows');
insert into petshop (name, age, kind) values ('Hebert', 13, 'King vulture');
insert into petshop (name, age, kind) values ('Wendie', 6, 'Oystercatcher, blackish');
insert into petshop (name, age, kind) values ('Joycelin', 57, 'Red-tailed wambenger');
insert into petshop (name, age, kind) values ('Sondra', 6, 'Jackrabbit, white-tailed');
insert into petshop (name, age, kind) values ('Callida', 6, 'Common pheasant');
insert into petshop (name, age, kind) values ('Betti', 13, 'Zorro, common');
insert into petshop (name, age, kind) values ('Vivyanne', 60, 'Wallaby, whip-tailed');
insert into petshop (name, age, kind) values ('Ame', 43, 'Suricate');
insert into petshop (name, age, kind) values ('Melvyn', 12, 'Verreaux''s sifaka');
insert into petshop (name, age, kind) values ('Zulema', 25, 'Sandpiper, spotted wood');
insert into petshop (name, age, kind) values ('Doralyn', 30, 'Zebra, plains');
insert into petshop (name, age, kind) values ('Hillery', 4, 'Falcon, prairie');
insert into petshop (name, age, kind) values ('Genna', 7, 'Asian elephant');
insert into petshop (name, age, kind) values ('Gerard', 14, 'Praying mantis (unidentified)');
insert into petshop (name, age, kind) values ('Rolando', 17, 'Egret, snowy');
insert into petshop (name, age, kind) values ('Raffaello', 3, 'Badger, honey');
insert into petshop (name, age, kind) values ('Sal', 5, 'Starling, superb');
insert into petshop (name, age, kind) values ('Harrison', 37, 'Lemur, lesser mouse');
insert into petshop (name, age, kind) values ('Raphaela', 88, 'Brindled gnu');
insert into petshop (name, age, kind) values ('Ellyn', 21, 'Tortoise, radiated');
insert into petshop (name, age, kind) values ('Sascha', 39, 'Sidewinder');
insert into petshop (name, age, kind) values ('Efren', 51, 'Cat, long-tailed spotted');
insert into petshop (name, age, kind) values ('Rossie', 33, 'Wallaby, bennett''s');
insert into petshop (name, age, kind) values ('Fleur', 24, 'Racer, american');
insert into petshop (name, age, kind) values ('Dell', 64, 'Black-tailed prairie dog');
insert into petshop (name, age, kind) values ('Kaila', 94, 'Snake, eastern indigo');
insert into petshop (name, age, kind) values ('Rikki', 27, 'Galapagos tortoise');
insert into petshop (name, age, kind) values ('Bernice', 97, 'Wallaby, red-necked');
insert into petshop (name, age, kind) values ('Pamelina', 52, 'Carpet python');
insert into petshop (name, age, kind) values ('Amii', 39, 'Possum, western pygmy');
insert into petshop (name, age, kind) values ('Vivienne', 57, 'Sheathbill, snowy');
insert into petshop (name, age, kind) values ('Paddie', 29, 'Fat-tailed dunnart');
insert into petshop (name, age, kind) values ('Galvin', 19, 'Parakeet, rose-ringed');
insert into petshop (name, age, kind) values ('Tudor', 58, 'Lion, south american sea');
insert into petshop (name, age, kind) values ('Diego', 8, 'Pie, indian tree');
insert into petshop (name, age, kind) values ('Penny', 28, 'Pelican, great white');
insert into petshop (name, age, kind) values ('Zia', 80, 'Lemur, ring-tailed');
insert into petshop (name, age, kind) values ('Theodor', 1, 'Rabbit, eastern cottontail');
insert into petshop (name, age, kind) values ('Ana', 47, 'Squirrel, golden-mantled ground');
insert into petshop (name, age, kind) values ('Mario', 45, 'Duck, white-faced whistling');
insert into petshop (name, age, kind) values ('Garik', 70, 'Turtle, snake-necked');
insert into petshop (name, age, kind) values ('Sandra', 21, 'Monitor, white-throated');
insert into petshop (name, age, kind) values ('Meggy', 9, 'Reindeer');
insert into petshop (name, age, kind) values ('Ned', 2, 'Rat, white-faced tree');
insert into petshop (name, age, kind) values ('Gabi', 13, 'Mexican boa');
insert into petshop (name, age, kind) values ('Nevsa', 56, 'Shrew, mandras tree');
insert into petshop (name, age, kind) values ('Sophi', 80, 'Dog, black-tailed prairie');
insert into petshop (name, age, kind) values ('Kaleena', 75, 'Urial');
insert into petshop (name, age, kind) values ('Kristofor', 19, 'Common wombat');
insert into petshop (name, age, kind) values ('Jefferey', 16, 'Shelduck, european');
insert into petshop (name, age, kind) values ('Byrle', 73, 'Sloth, pale-throated three-toed');
insert into petshop (name, age, kind) values ('Neely', 80, 'Kangaroo, eastern grey');
insert into petshop (name, age, kind) values ('Petra', 92, 'Lourie, grey');
insert into petshop (name, age, kind) values ('Micheil', 77, 'Deer, swamp');
insert into petshop (name, age, kind) values ('Harriot', 31, 'Azara''s zorro');
insert into petshop (name, age, kind) values ('Dante', 54, 'Vulture, black');
insert into petshop (name, age, kind) values ('Griswold', 71, 'Southern black-backed gull');
insert into petshop (name, age, kind) values ('Hilda', 82, 'Vulture, lappet-faced');
insert into petshop (name, age, kind) values ('Dionne', 58, 'Jaguar');
insert into petshop (name, age, kind) values ('Gwenneth', 100, 'Common mynah');
insert into petshop (name, age, kind) values ('Halli', 9, 'Buttermilk snake');
insert into petshop (name, age, kind) values ('Alejandrina', 79, 'European red squirrel');
insert into petshop (name, age, kind) values ('Jule', 6, 'Cormorant, pied');
insert into petshop (name, age, kind) values ('Charlie', 53, 'Red brocket');
insert into petshop (name, age, kind) values ('Marlene', 48, 'Flicker, campo');
insert into petshop (name, age, kind) values ('Viviyan', 23, 'Nyala');
insert into petshop (name, age, kind) values ('Marigold', 39, 'Ring-tailed lemur');
insert into petshop (name, age, kind) values ('Tracie', 58, 'Greater roadrunner');
insert into petshop (name, age, kind) values ('Clemence', 63, 'Civet cat');
insert into petshop (name, age, kind) values ('Darrel', 40, 'Beisa oryx');
insert into petshop (name, age, kind) values ('Sharleen', 62, 'Groundhog');
insert into petshop (name, age, kind) values ('Maje', 96, 'Lizard, giant girdled');
insert into petshop (name, age, kind) values ('Torrin', 51, 'Common brushtail possum');
insert into petshop (name, age, kind) values ('Porter', 12, 'Royal tern');
insert into petshop (name, age, kind) values ('Paxon', 32, 'Shrike, crimson-breasted');
insert into petshop (name, age, kind) values ('Madlin', 19, 'Owl, madagascar hawk');
insert into petshop (name, age, kind) values ('Kip', 20, 'Red-tailed wambenger');
insert into petshop (name, age, kind) values ('Liva', 82, 'Cormorant, large');
insert into petshop (name, age, kind) values ('Melvyn', 97, 'Asian lion');
insert into petshop (name, age, kind) values ('Kathryn', 19, 'Raven, cape');
insert into petshop (name, age, kind) values ('Vern', 90, 'Manatee');
insert into petshop (name, age, kind) values ('Rivkah', 1, 'Genoveva');
insert into petshop (name, age, kind) values ('Curry', 98, 'Urial');
insert into petshop (name, age, kind) values ('Phil', 30, 'Porcupine, indian');
insert into petshop (name, age, kind) values ('Hayes', 17, 'Otter, small-clawed');
insert into petshop (name, age, kind) values ('Papagena', 84, 'Gemsbok');
insert into petshop (name, age, kind) values ('Minny', 64, 'Little cormorant');
insert into petshop (name, age, kind) values ('Tan', 69, 'Flicker, field');
insert into petshop (name, age, kind) values ('Richmound', 40, 'Yellow baboon');
insert into petshop (name, age, kind) values ('Carver', 61, 'Francolin, swainson''s');
insert into petshop (name, age, kind) values ('Amandi', 91, 'Frogmouth, tawny');
insert into petshop (name, age, kind) values ('Maurene', 75, 'Russian dragonfly');
insert into petshop (name, age, kind) values ('Ermengarde', 2, 'Nuthatch, red-breasted');
insert into petshop (name, age, kind) values ('Petronille', 66, 'Long-billed cockatoo');
insert into petshop (name, age, kind) values ('Ardenia', 44, 'Mongoose, banded');
insert into petshop (name, age, kind) values ('Lilah', 10, 'North American red fox');
insert into petshop (name, age, kind) values ('Mariele', 91, 'Praying mantis (unidentified)');
insert into petshop (name, age, kind) values ('Sheffield', 62, 'Rat, desert kangaroo');
insert into petshop (name, age, kind) values ('Weber', 93, 'Worm snake (unidentified)');
insert into petshop (name, age, kind) values ('Aldridge', 15, 'Long-tailed spotted cat');
insert into petshop (name, age, kind) values ('Humberto', 84, 'North American river otter');
insert into petshop (name, age, kind) values ('Rogerio', 12, 'Eagle, golden');
insert into petshop (name, age, kind) values ('Sylas', 28, 'Lion, african');
insert into petshop (name, age, kind) values ('Lara', 10, 'Currasow (unidentified)');
insert into petshop (name, age, kind) values ('Olenka', 86, 'Mocking cliffchat');
insert into petshop (name, age, kind) values ('Rick', 89, 'Mongoose, small indian');
insert into petshop (name, age, kind) values ('Garrek', 6, 'Hedgehog, south african');
insert into petshop (name, age, kind) values ('Ugo', 47, 'Hyena, brown');
insert into petshop (name, age, kind) values ('Felicdad', 84, 'Possum, pygmy');
insert into petshop (name, age, kind) values ('Yoshi', 92, 'Eastern fox squirrel');
insert into petshop (name, age, kind) values ('Demeter', 71, 'Baboon, yellow');
insert into petshop (name, age, kind) values ('Arleen', 82, 'Chital');
insert into petshop (name, age, kind) values ('Nelson', 88, 'Porcupine, african');
insert into petshop (name, age, kind) values ('Chryste', 47, 'Flamingo, chilean');
insert into petshop (name, age, kind) values ('Alberik', 96, 'Swallow-tail gull');
insert into petshop (name, age, kind) values ('Jania', 32, 'White-fronted bee-eater');
insert into petshop (name, age, kind) values ('Bernice', 7, 'Steller''s sea lion');
insert into petshop (name, age, kind) values ('Bradan', 19, 'Squirrel, malabar');
insert into petshop (name, age, kind) values ('Rani', 74, 'Beaver, north american');
insert into petshop (name, age, kind) values ('Joya', 41, 'Australian sea lion');
insert into petshop (name, age, kind) values ('Kora', 74, 'Cook''s tree boa');
insert into petshop (name, age, kind) values ('Marguerite', 3, 'Frilled dragon');
insert into petshop (name, age, kind) values ('Auguste', 99, 'Galapagos albatross');
insert into petshop (name, age, kind) values ('Lurlene', 69, 'African pied wagtail');
insert into petshop (name, age, kind) values ('Christy', 15, 'Fox, silver-backed');
insert into petshop (name, age, kind) values ('Dell', 93, 'Sockeye salmon');
insert into petshop (name, age, kind) values ('Lenci', 65, 'Eagle, pallas''s fish');
insert into petshop (name, age, kind) values ('Ianthe', 64, 'Jackal, indian');
insert into petshop (name, age, kind) values ('Gae', 45, 'Eastern diamondback rattlesnake');
insert into petshop (name, age, kind) values ('Dougie', 8, 'Red-shouldered glossy starling');
insert into petshop (name, age, kind) values ('Frannie', 18, 'Shelduck, european');
insert into petshop (name, age, kind) values ('Sapphira', 82, 'Ibis, sacred');
insert into petshop (name, age, kind) values ('Edna', 71, 'Albatross, galapagos');
insert into petshop (name, age, kind) values ('Nikolas', 5, 'Kookaburra, laughing');
insert into petshop (name, age, kind) values ('Junie', 94, 'Bee-eater, nubian');
insert into petshop (name, age, kind) values ('Wanids', 83, 'Goldeneye, common');
insert into petshop (name, age, kind) values ('Lyn', 68, 'Zebra, plains');
insert into petshop (name, age, kind) values ('Berri', 70, 'Blackbird, red-winged');
insert into petshop (name, age, kind) values ('Valentia', 59, 'Salmon pink bird eater tarantula');
insert into petshop (name, age, kind) values ('Dulcine', 80, 'Eagle, long-crested hawk');
insert into petshop (name, age, kind) values ('Leesa', 27, 'Gaur');
insert into petshop (name, age, kind) values ('Ash', 76, 'Common pheasant');
insert into petshop (name, age, kind) values ('Constantine', 75, 'Cook''s tree boa');
insert into petshop (name, age, kind) values ('Wilbur', 46, 'Grenadier, purple');
insert into petshop (name, age, kind) values ('Lorrin', 75, 'Rat, arboral spiny');
insert into petshop (name, age, kind) values ('Lindie', 60, 'Lappet-faced vulture');
insert into petshop (name, age, kind) values ('Holly', 91, 'Barbet, crested');
insert into petshop (name, age, kind) values ('Clovis', 83, 'Steenbuck');
insert into petshop (name, age, kind) values ('Monah', 3, 'Emerald-spotted wood dove');
insert into petshop (name, age, kind) values ('Norri', 79, 'Zebra, plains');
insert into petshop (name, age, kind) values ('Rhonda', 32, 'Hare, arctic');
insert into petshop (name, age, kind) values ('Rozelle', 88, 'White-fronted capuchin');
insert into petshop (name, age, kind) values ('Bonni', 61, 'Badger, american');
insert into petshop (name, age, kind) values ('Arin', 74, 'Duiker, common');
insert into petshop (name, age, kind) values ('Anne-marie', 53, 'Toucan, white-throated');
insert into petshop (name, age, kind) values ('Geoffrey', 26, 'Indian red admiral');
insert into petshop (name, age, kind) values ('Deana', 34, 'Glider, feathertail');
insert into petshop (name, age, kind) values ('Susy', 76, 'Rufous tree pie');
insert into petshop (name, age, kind) values ('Angela', 25, 'Cougar');
insert into petshop (name, age, kind) values ('West', 50, 'Cook''s tree boa');
insert into petshop (name, age, kind) values ('Shellie', 12, 'Dragon, western bearded');
insert into petshop (name, age, kind) values ('Daile', 26, 'Spoonbill, white');
insert into petshop (name, age, kind) values ('Hewie', 50, 'Egret, snowy');
insert into petshop (name, age, kind) values ('Enrico', 100, 'Canadian tiger swallowtail butterfly');
insert into petshop (name, age, kind) values ('Emlen', 1, 'Hartebeest, red');
insert into petshop (name, age, kind) values ('Barton', 92, 'Southern hairy-nosed wombat');
insert into petshop (name, age, kind) values ('Margarette', 76, 'Nilgai');
insert into petshop (name, age, kind) values ('Kerwinn', 97, 'Black-backed magpie');
insert into petshop (name, age, kind) values ('Margaretta', 99, 'Water legaan');
insert into petshop (name, age, kind) values ('Guinna', 35, 'Dolphin, bottle-nose');
insert into petshop (name, age, kind) values ('Cynde', 55, 'Spurfowl, yellow-necked');
insert into petshop (name, age, kind) values ('Petronille', 28, 'Ibis, puna');
insert into petshop (name, age, kind) values ('Hughie', 1, 'Rufous tree pie');
insert into petshop (name, age, kind) values ('Lyon', 63, 'Mynah, indian');
insert into petshop (name, age, kind) values ('Juliann', 25, 'Lesser flamingo');
insert into petshop (name, age, kind) values ('Vi', 85, 'Porcupine, north american');
insert into petshop (name, age, kind) values ('Nickie', 31, 'Gulls (unidentified)');
insert into petshop (name, age, kind) values ('Dorene', 56, 'Nelson ground squirrel');
insert into petshop (name, age, kind) values ('Gordy', 88, 'Yellow-throated sandgrouse');
insert into petshop (name, age, kind) values ('Midge', 100, 'Hartebeest, red');
insert into petshop (name, age, kind) values ('Lucilia', 25, 'Capybara');
insert into petshop (name, age, kind) values ('Brandtr', 74, 'White-winged tern');
insert into petshop (name, age, kind) values ('Germain', 67, 'Bushpig');
insert into petshop (name, age, kind) values ('Rosette', 15, 'Cobra, cape');
insert into petshop (name, age, kind) values ('Nathanial', 44, 'Mynah, common');
insert into petshop (name, age, kind) values ('Dulcea', 8, 'Reindeer');
insert into petshop (name, age, kind) values ('Nisse', 5, 'Squirrel, grey-footed');
insert into petshop (name, age, kind) values ('Gunther', 9, 'Dove, laughing');
insert into petshop (name, age, kind) values ('Valera', 77, 'Mynah, indian');
insert into petshop (name, age, kind) values ('Odo', 89, 'Paradoxure');
insert into petshop (name, age, kind) values ('Sigismondo', 77, 'Kangaroo, black-faced');
insert into petshop (name, age, kind) values ('Tami', 38, 'Cat, miner''s');
insert into petshop (name, age, kind) values ('Franciskus', 85, 'Onager');
insert into petshop (name, age, kind) values ('Ingrim', 53, 'Rhea, common');
insert into petshop (name, age, kind) values ('Matelda', 15, 'Black rhinoceros');
insert into petshop (name, age, kind) values ('Quillan', 25, 'Pigeon, wood');
insert into petshop (name, age, kind) values ('Quintilla', 89, 'Turtle, eastern box');
insert into petshop (name, age, kind) values ('Maddie', 2, 'Colobus, black and white');
insert into petshop (name, age, kind) values ('Vin', 2, 'Camel, dromedary');
insert into petshop (name, age, kind) values ('Brynne', 82, 'Arctic fox');
insert into petshop (name, age, kind) values ('Winifield', 93, 'Squirrel, smith''s bush');
insert into petshop (name, age, kind) values ('Karrie', 37, 'Ibis, glossy');
insert into petshop (name, age, kind) values ('Ronni', 4, 'Lizard, goanna');
insert into petshop (name, age, kind) values ('Nerti', 91, 'Blue wildebeest');
insert into petshop (name, age, kind) values ('Somerset', 50, 'Black-crowned crane');
insert into petshop (name, age, kind) values ('Raymund', 59, 'Whale, baleen');
insert into petshop (name, age, kind) values ('Cariotta', 49, 'Cheetah');
insert into petshop (name, age, kind) values ('Emmey', 40, 'Albatross, waved');
insert into petshop (name, age, kind) values ('Roman', 96, 'Stork, white');
insert into petshop (name, age, kind) values ('Cameron', 43, 'Lemming, arctic');
insert into petshop (name, age, kind) values ('Harmonie', 40, 'Pelican, great white');
insert into petshop (name, age, kind) values ('Maryanna', 99, 'Small-spotted genet');
insert into petshop (name, age, kind) values ('Bourke', 50, 'Spur-winged goose');
insert into petshop (name, age, kind) values ('Lurline', 5, 'Meerkat');
insert into petshop (name, age, kind) values ('Drusilla', 42, 'Red brocket');
insert into petshop (name, age, kind) values ('Ardelis', 37, 'Brush-tailed rat kangaroo');
insert into petshop (name, age, kind) values ('Saidee', 84, 'Little cormorant');
insert into petshop (name, age, kind) values ('Sapphira', 47, 'Dusky rattlesnake');
insert into petshop (name, age, kind) values ('Friedrick', 3, 'Flicker, field');
insert into petshop (name, age, kind) values ('Neila', 8, 'Turkey, wild');
insert into petshop (name, age, kind) values ('Danette', 16, 'Brown lemur');
insert into petshop (name, age, kind) values ('Alanah', 20, 'Southern ground hornbill');
insert into petshop (name, age, kind) values ('Lois', 60, 'Little brown bat');
insert into petshop (name, age, kind) values ('Malvina', 49, 'Green heron');
insert into petshop (name, age, kind) values ('Aprilette', 35, 'Lorikeet, scaly-breasted');
insert into petshop (name, age, kind) values ('Gerrard', 52, 'Snake, green vine');
insert into petshop (name, age, kind) values ('Gaspard', 17, 'Osprey');
insert into petshop (name, age, kind) values ('Corene', 44, 'Pelican, great white');
insert into petshop (name, age, kind) values ('Debee', 7, 'Swamp deer');
insert into petshop (name, age, kind) values ('Viva', 82, 'Springhare');
insert into petshop (name, age, kind) values ('Nadia', 83, 'Cormorant, javanese');
insert into petshop (name, age, kind) values ('Wang', 59, 'Greater flamingo');
insert into petshop (name, age, kind) values ('Trudey', 41, 'Lion, southern sea');
insert into petshop (name, age, kind) values ('Lenka', 44, 'Great cormorant');
insert into petshop (name, age, kind) values ('Theadora', 83, 'Deer, swamp');
insert into petshop (name, age, kind) values ('Ethelind', 25, 'Sheep, stone');
insert into petshop (name, age, kind) values ('Gail', 57, 'Northern phalarope');
insert into petshop (name, age, kind) values ('Barnie', 16, 'Square-lipped rhinoceros');
insert into petshop (name, age, kind) values ('Letizia', 27, 'Marmot, hoary');
insert into petshop (name, age, kind) values ('Maddy', 48, 'Fox, bat-eared');
insert into petshop (name, age, kind) values ('Gabbi', 22, 'Northern fur seal');
insert into petshop (name, age, kind) values ('Turner', 54, 'Legaan, Monitor (unidentified)');
insert into petshop (name, age, kind) values ('Bastian', 87, 'North American red fox');
insert into petshop (name, age, kind) values ('Ingra', 14, 'North American red fox');
insert into petshop (name, age, kind) values ('Kirstin', 17, 'Green heron');
insert into petshop (name, age, kind) values ('Myrwyn', 98, 'Cape clawless otter');
insert into petshop (name, age, kind) values ('Claudine', 78, 'African snake (unidentified)');
insert into petshop (name, age, kind) values ('Rollins', 62, 'Swamp deer');
insert into petshop (name, age, kind) values ('Hi', 39, 'Marabou stork');
insert into petshop (name, age, kind) values ('Oliver', 96, 'Bear, polar');
insert into petshop (name, age, kind) values ('Lisabeth', 1, 'Dolphin, bottle-nose');
insert into petshop (name, age, kind) values ('Marlie', 47, 'Common ringtail');
insert into petshop (name, age, kind) values ('Camila', 94, 'Jackrabbit, white-tailed');
insert into petshop (name, age, kind) values ('Kamila', 2, 'Common seal');
insert into petshop (name, age, kind) values ('Lovell', 81, 'African darter');
insert into petshop (name, age, kind) values ('Jarrad', 7, 'Eagle, white-bellied sea');
insert into petshop (name, age, kind) values ('Ynez', 84, 'Stork, painted');
insert into petshop (name, age, kind) values ('Theodore', 87, 'North American river otter');
insert into petshop (name, age, kind) values ('Flori', 79, 'Asian openbill');
insert into petshop (name, age, kind) values ('Johnny', 66, 'Otter, african clawless');
insert into petshop (name, age, kind) values ('Paddy', 71, 'Common waterbuck');
insert into petshop (name, age, kind) values ('Celesta', 18, 'Crow, american');
insert into petshop (name, age, kind) values ('Cyb', 44, 'White-cheeked pintail');
insert into petshop (name, age, kind) values ('Rey', 4, 'Dove, galapagos');
insert into petshop (name, age, kind) values ('Nicoline', 50, 'Oryx, fringe-eared');
insert into petshop (name, age, kind) values ('Garnette', 15, 'Yellow baboon');
insert into petshop (name, age, kind) values ('Sandro', 48, 'Swallow-tail gull');
insert into petshop (name, age, kind) values ('Tiler', 3, 'Ground monitor (unidentified)');
insert into petshop (name, age, kind) values ('Retha', 100, 'Wallaby, dama');
insert into petshop (name, age, kind) values ('Artemus', 23, 'Cat, kaffir');
insert into petshop (name, age, kind) values ('Baldwin', 13, 'Coke''s hartebeest');
insert into petshop (name, age, kind) values ('Lacie', 81, 'Monkey, rhesus');
insert into petshop (name, age, kind) values ('Simmonds', 41, 'Tamandua, southern');
insert into petshop (name, age, kind) values ('Tybie', 58, 'Vulture, white-rumped');
insert into petshop (name, age, kind) values ('Blake', 78, 'Giraffe');
insert into petshop (name, age, kind) values ('Irv', 59, 'Toddy cat');
insert into petshop (name, age, kind) values ('Ealasaid', 75, 'Cormorant, neotropic');
insert into petshop (name, age, kind) values ('Jessalyn', 55, 'Asian water buffalo');
insert into petshop (name, age, kind) values ('Bentley', 66, 'Water moccasin');
insert into petshop (name, age, kind) values ('Mirna', 19, 'Red kangaroo');
insert into petshop (name, age, kind) values ('Eldredge', 37, 'Kangaroo, western grey');
insert into petshop (name, age, kind) values ('Janessa', 89, 'Bee-eater, white-fronted');
insert into petshop (name, age, kind) values ('Kingsley', 56, 'Fox, cape');
insert into petshop (name, age, kind) values ('Towney', 69, 'Trumpeter swan');
insert into petshop (name, age, kind) values ('Maurits', 7, 'Great egret');
insert into petshop (name, age, kind) values ('Rasia', 56, 'Bird, black-throated butcher');
insert into petshop (name, age, kind) values ('Colan', 91, 'Mexican beaded lizard');
insert into petshop (name, age, kind) values ('Zarah', 96, 'Stork, woolly-necked');
insert into petshop (name, age, kind) values ('Upton', 9, 'Clark''s nutcracker');
insert into petshop (name, age, kind) values ('Marmaduke', 58, 'Squirrel, palm');
insert into petshop (name, age, kind) values ('Timmi', 46, 'Penguin, magellanic');
insert into petshop (name, age, kind) values ('Verne', 54, 'Richardson''s ground squirrel');
insert into petshop (name, age, kind) values ('Lindon', 42, 'Macaque, japanese');
insert into petshop (name, age, kind) values ('Bobina', 5, 'Hen, sage');
insert into petshop (name, age, kind) values ('Kearney', 99, 'Robin, white-throated');
insert into petshop (name, age, kind) values ('Demetre', 70, 'Koala');
insert into petshop (name, age, kind) values ('Zed', 99, 'King vulture');
insert into petshop (name, age, kind) values ('Jason', 86, 'Lemur, brown');
insert into petshop (name, age, kind) values ('Mic', 95, 'Blue-breasted cordon bleu');
insert into petshop (name, age, kind) values ('Cassandry', 13, 'White-browed owl');
insert into petshop (name, age, kind) values ('Maurie', 50, 'Crested porcupine');
insert into petshop (name, age, kind) values ('Celestyn', 97, 'Great horned owl');
insert into petshop (name, age, kind) values ('Alyssa', 93, 'Fowl, helmeted guinea');
insert into petshop (name, age, kind) values ('Courtnay', 22, 'Blacksmith plover');
insert into petshop (name, age, kind) values ('Mikel', 6, 'Phalarope, grey');
insert into petshop (name, age, kind) values ('Elnora', 21, 'White-necked raven');
insert into petshop (name, age, kind) values ('Jordana', 84, 'Tinamou, elegant crested');
insert into petshop (name, age, kind) values ('Ermengarde', 43, 'Bat-eared fox');
insert into petshop (name, age, kind) values ('Smitty', 100, 'Owl, madagascar hawk');
insert into petshop (name, age, kind) values ('Estell', 19, 'Flamingo, greater');
insert into petshop (name, age, kind) values ('Harland', 100, 'Greater kudu');
insert into petshop (name, age, kind) values ('Remy', 93, 'Dragonfly, russian');
insert into petshop (name, age, kind) values ('Rhona', 20, 'Steenbok');
insert into petshop (name, age, kind) values ('Gunter', 44, 'Ostrich');
insert into petshop (name, age, kind) values ('Clarinda', 37, 'Shark, blue');
insert into petshop (name, age, kind) values ('Aubree', 54, 'Madagascar hawk owl');
insert into petshop (name, age, kind) values ('Terri', 11, 'Javan gold-spotted mongoose');
insert into petshop (name, age, kind) values ('Marlane', 48, 'Dark-winged trumpeter');
insert into petshop (name, age, kind) values ('Jedd', 72, 'Zebra, plains');
insert into petshop (name, age, kind) values ('Kimberlyn', 15, 'Spur-winged goose');
insert into petshop (name, age, kind) values ('Amabelle', 73, 'Grizzly bear');
insert into petshop (name, age, kind) values ('Kendra', 47, 'Bird, bare-faced go away');
insert into petshop (name, age, kind) values ('Evvie', 3, 'Genoveva');
insert into petshop (name, age, kind) values ('Yurik', 48, 'Jacana, african');
insert into petshop (name, age, kind) values ('Lynnelle', 40, 'Monitor, white-throated');
insert into petshop (name, age, kind) values ('Wyn', 90, 'Ground legaan');
insert into petshop (name, age, kind) values ('Erinn', 23, 'Hartebeest, coke''s');
insert into petshop (name, age, kind) values ('Derick', 85, 'Hyena, brown');
insert into petshop (name, age, kind) values ('Jenn', 84, 'Cobra (unidentified)');
insert into petshop (name, age, kind) values ('Roderic', 58, 'Yellow-billed stork');
insert into petshop (name, age, kind) values ('Hortensia', 29, 'Ferret, black-footed');
insert into petshop (name, age, kind) values ('Anabella', 39, 'Waxbill, blue');
insert into petshop (name, age, kind) values ('Ginger', 74, 'Silver-backed fox');
insert into petshop (name, age, kind) values ('Bengt', 47, 'Three-banded plover');
insert into petshop (name, age, kind) values ('Nerissa', 100, 'Three-banded plover');
insert into petshop (name, age, kind) values ('Leontine', 79, 'Beisa oryx');
insert into petshop (name, age, kind) values ('Kary', 15, 'Sunbird, lesser double-collared');
insert into petshop (name, age, kind) values ('Hugibert', 3, 'Nubian bee-eater');
insert into petshop (name, age, kind) values ('Thomasina', 20, 'Gerenuk');
insert into petshop (name, age, kind) values ('Filmore', 49, 'Coatimundi, ring-tailed');
insert into petshop (name, age, kind) values ('Diandra', 28, 'Kingfisher, malachite');
insert into petshop (name, age, kind) values ('Casandra', 75, 'Fox, savanna');
insert into petshop (name, age, kind) values ('Wesley', 45, 'Shark, blue');
insert into petshop (name, age, kind) values ('Roxie', 11, 'Woodpecker, downy');
insert into petshop (name, age, kind) values ('Antonino', 7, 'Stick insect');
insert into petshop (name, age, kind) values ('Rivkah', 11, 'Slender loris');
insert into petshop (name, age, kind) values ('Barbara', 6, 'Blackish oystercatcher');
insert into petshop (name, age, kind) values ('Buddy', 36, 'Thrasher, curve-billed');
insert into petshop (name, age, kind) values ('Hali', 30, 'Yellow-crowned night heron');
insert into petshop (name, age, kind) values ('Ode', 95, 'Sloth, two-toed');
insert into petshop (name, age, kind) values ('Brocky', 13, 'Shrike, crimson-breasted');
insert into petshop (name, age, kind) values ('Garrott', 45, 'Sheep, red');
insert into petshop (name, age, kind) values ('Rockwell', 73, 'House crow');
insert into petshop (name, age, kind) values ('Casie', 78, 'Margay');
insert into petshop (name, age, kind) values ('Flin', 37, 'Blackbird, red-winged');
insert into petshop (name, age, kind) values ('Lilias', 32, 'Cat, civet');
insert into petshop (name, age, kind) values ('Bibby', 95, 'Bobcat');
insert into petshop (name, age, kind) values ('Danika', 74, 'Savanna baboon');
insert into petshop (name, age, kind) values ('Boothe', 87, 'Cormorant, flightless');
insert into petshop (name, age, kind) values ('Silas', 57, 'Bengal vulture');
insert into petshop (name, age, kind) values ('Berny', 44, 'Monkey, rhesus');
insert into petshop (name, age, kind) values ('Adriane', 42, 'Sunbird, lesser double-collared');
insert into petshop (name, age, kind) values ('Glenda', 97, 'Black-tailed deer');
insert into petshop (name, age, kind) values ('Adey', 21, 'Flamingo, greater');
insert into petshop (name, age, kind) values ('Annalise', 18, 'Lesser double-collared sunbird');
insert into petshop (name, age, kind) values ('Christye', 76, 'Red-winged blackbird');
insert into petshop (name, age, kind) values ('Jobie', 82, 'Nelson ground squirrel');
insert into petshop (name, age, kind) values ('Clyve', 22, 'Owl, great horned');
insert into petshop (name, age, kind) values ('Corly', 15, 'Beaver, american');
insert into petshop (name, age, kind) values ('Lurette', 56, 'Fox, cape');
insert into petshop (name, age, kind) values ('Terza', 77, 'Dragon, western bearded');
insert into petshop (name, age, kind) values ('Audry', 99, 'Macaw, blue and gold');
insert into petshop (name, age, kind) values ('Brenn', 57, 'Ornate rock dragon');
insert into petshop (name, age, kind) values ('Tore', 33, 'Gonolek, burchell''s');
insert into petshop (name, age, kind) values ('Aloysius', 30, 'Capuchin, black-capped');
insert into petshop (name, age, kind) values ('Paten', 84, 'Wild boar');
insert into petshop (name, age, kind) values ('Bamby', 30, 'Peregrine falcon');
insert into petshop (name, age, kind) values ('Kellsie', 1, 'South American sea lion');
insert into petshop (name, age, kind) values ('Janice', 5, 'Baboon, savanna');
insert into petshop (name, age, kind) values ('Leighton', 20, 'Eurasian beaver');
insert into petshop (name, age, kind) values ('Peyton', 84, 'Rainbow lory');
insert into petshop (name, age, kind) values ('Rodie', 72, 'Gaur');
insert into petshop (name, age, kind) values ('Raf', 57, 'Swamp deer');
insert into petshop (name, age, kind) values ('Cross', 86, 'Beaver, american');
insert into petshop (name, age, kind) values ('Kara-lynn', 6, 'Fox, cape');
insert into petshop (name, age, kind) values ('Roz', 50, 'Rhesus monkey');
insert into petshop (name, age, kind) values ('Terri', 84, 'Glossy starling (unidentified)');
insert into petshop (name, age, kind) values ('Thadeus', 57, 'Fox, bat-eared');
insert into petshop (name, age, kind) values ('Reidar', 96, 'Mountain lion');
insert into petshop (name, age, kind) values ('Jammie', 80, 'Mourning collared dove');
insert into petshop (name, age, kind) values ('Laurena', 42, 'Tinamou, elegant crested');
insert into petshop (name, age, kind) values ('Pierrette', 86, 'Pygmy possum');
insert into petshop (name, age, kind) values ('Kingston', 51, 'Long-billed corella');
insert into petshop (name, age, kind) values ('Arnaldo', 8, 'Siskin, pine');
insert into petshop (name, age, kind) values ('Katinka', 43, 'Nuthatch, red-breasted');
insert into petshop (name, age, kind) values ('Jayme', 59, 'Stork, white-necked');
insert into petshop (name, age, kind) values ('Adham', 83, 'Galapagos mockingbird');
insert into petshop (name, age, kind) values ('Ernst', 81, 'South American meadowlark (unidentified)');
insert into petshop (name, age, kind) values ('Kincaid', 5, 'Swainson''s francolin');
insert into petshop (name, age, kind) values ('Denys', 22, 'Wallaby, river');
insert into petshop (name, age, kind) values ('Engracia', 51, 'Bushpig');
insert into petshop (name, age, kind) values ('Tad', 48, 'American crow');
insert into petshop (name, age, kind) values ('Whittaker', 95, 'Skunk, striped');
insert into petshop (name, age, kind) values ('Mordecai', 85, 'Common pheasant');
insert into petshop (name, age, kind) values ('Benedict', 29, 'Elephant, african');
insert into petshop (name, age, kind) values ('Drucy', 96, 'Bateleur eagle');
insert into petshop (name, age, kind) values ('Patin', 73, 'Violet-eared waxbill');
insert into petshop (name, age, kind) values ('Julita', 55, 'Bird (unidentified)');
insert into petshop (name, age, kind) values ('Dorothee', 47, 'Rhesus monkey');
insert into petshop (name, age, kind) values ('Floris', 100, 'Barrows goldeneye');
insert into petshop (name, age, kind) values ('Catrina', 49, 'Stanley bustard');
insert into petshop (name, age, kind) values ('Keefer', 97, 'Leopard, indian');
insert into petshop (name, age, kind) values ('Jasmin', 48, 'Cape starling');
insert into petshop (name, age, kind) values ('Ham', 63, 'Cormorant, large');
insert into petshop (name, age, kind) values ('Jillayne', 42, 'Eagle, white-bellied sea');
insert into petshop (name, age, kind) values ('Michale', 40, 'Kudu, greater');
insert into petshop (name, age, kind) values ('Laurent', 97, 'Small-toothed palm civet');
insert into petshop (name, age, kind) values ('Kinsley', 36, 'Bird, pied butcher');
insert into petshop (name, age, kind) values ('Kit', 22, 'Lizard, frilled');
insert into petshop (name, age, kind) values ('Bourke', 12, 'Three-banded plover');
insert into petshop (name, age, kind) values ('Winni', 40, 'Armadillo, giant');
insert into petshop (name, age, kind) values ('Gun', 60, 'Turtle, long-necked');
insert into petshop (name, age, kind) values ('Engracia', 35, 'Squirrel, pine');
insert into petshop (name, age, kind) values ('Hana', 41, 'Tortoise, desert');
insert into petshop (name, age, kind) values ('Salem', 43, 'Feathertail glider');
insert into petshop (name, age, kind) values ('Carl', 44, 'Butterfly, tropical buckeye');
insert into petshop (name, age, kind) values ('Lurlene', 64, 'Alligator, mississippi');
insert into petshop (name, age, kind) values ('Armin', 99, 'Emu');
insert into petshop (name, age, kind) values ('Terry', 41, 'Sally lightfoot crab');
insert into petshop (name, age, kind) values ('Cornie', 51, 'Magpie, black-backed');
insert into petshop (name, age, kind) values ('Sasha', 31, 'Magistrate black colobus');
insert into petshop (name, age, kind) values ('Sharon', 43, 'Ocelot');
insert into petshop (name, age, kind) values ('Penelopa', 44, 'Gambel''s quail');
insert into petshop (name, age, kind) values ('Floria', 93, 'Waxbill, black-cheeked');
insert into petshop (name, age, kind) values ('Julie', 65, 'African skink');
insert into petshop (name, age, kind) values ('Sheilakathryn', 64, 'Yellow-bellied marmot');
insert into petshop (name, age, kind) values ('Otes', 1, 'Pied cormorant');
insert into petshop (name, age, kind) values ('Minerva', 64, 'Grey fox');
insert into petshop (name, age, kind) values ('Whitman', 86, 'Arctic fox');
insert into petshop (name, age, kind) values ('Sherry', 52, 'Grey fox');
insert into petshop (name, age, kind) values ('Sandor', 34, 'Eleven-banded armadillo (unidentified)');
insert into petshop (name, age, kind) values ('Lynea', 85, 'Japanese macaque');
insert into petshop (name, age, kind) values ('Arne', 21, 'Colobus, black and white');
insert into petshop (name, age, kind) values ('Maryjane', 94, 'Wallaby, red-necked');
insert into petshop (name, age, kind) values ('Abbe', 15, 'Fox, crab-eating');
insert into petshop (name, age, kind) values ('Jacques', 99, 'Grant''s gazelle');
insert into petshop (name, age, kind) values ('Trude', 97, 'Huron');
insert into petshop (name, age, kind) values ('Wynn', 45, 'Rhinoceros, white');
insert into petshop (name, age, kind) values ('Faustine', 90, 'Brown and yellow marshbird');
insert into petshop (name, age, kind) values ('Correna', 36, 'Pronghorn');
insert into petshop (name, age, kind) values ('Claybourne', 48, 'Wallaby, bennett''s');
insert into petshop (name, age, kind) values ('Camilla', 100, 'Stork, greater adjutant');
insert into petshop (name, age, kind) values ('Valerye', 61, 'Black swan');
insert into petshop (name, age, kind) values ('Gerri', 59, 'Legaan, water');
insert into petshop (name, age, kind) values ('Min', 84, 'Common rhea');
insert into petshop (name, age, kind) values ('Sherlocke', 47, 'Currasow (unidentified)');
insert into petshop (name, age, kind) values ('Sigrid', 84, 'Brown antechinus');
insert into petshop (name, age, kind) values ('Paule', 58, 'Tiger snake');
insert into petshop (name, age, kind) values ('Debee', 67, 'Gull, pacific');
insert into petshop (name, age, kind) values ('Aleta', 65, 'Olive baboon');
insert into petshop (name, age, kind) values ('Jamima', 2, 'Moorhen, purple');
insert into petshop (name, age, kind) values ('Victoria', 23, 'Collared peccary');
insert into petshop (name, age, kind) values ('Ad', 63, 'Agama lizard (unidentified)');
insert into petshop (name, age, kind) values ('Oren', 53, 'Common boubou shrike');
insert into petshop (name, age, kind) values ('Chlo', 67, 'Sheathbill, snowy');
insert into petshop (name, age, kind) values ('Neils', 77, 'Fox, silver-backed');
insert into petshop (name, age, kind) values ('Harlie', 10, 'Shrew, mandras tree');
insert into petshop (name, age, kind) values ('Guillema', 60, 'Ring-tailed lemur');
insert into petshop (name, age, kind) values ('Daren', 33, 'Numbat');
insert into petshop (name, age, kind) values ('Katey', 8, 'Northern elephant seal');
insert into petshop (name, age, kind) values ('Thorvald', 2, 'Gecko (unidentified)');
insert into petshop (name, age, kind) values ('Shayne', 65, 'Rattlesnake, eastern diamondback');
insert into petshop (name, age, kind) values ('Goraud', 22, 'Antelope ground squirrel');
insert into petshop (name, age, kind) values ('Vaclav', 65, 'Grizzly bear');
insert into petshop (name, age, kind) values ('Jolene', 87, 'American bighorn sheep');
insert into petshop (name, age, kind) values ('Brittni', 47, 'Green heron');
insert into petshop (name, age, kind) values ('Dale', 79, 'Vine snake (unidentified)');
insert into petshop (name, age, kind) values ('Cherry', 32, 'Crab, sally lightfoot');
insert into petshop (name, age, kind) values ('Carie', 29, 'Tsessebe');
insert into petshop (name, age, kind) values ('Anderson', 17, 'Galapagos albatross');
insert into petshop (name, age, kind) values ('Norry', 50, 'Asiatic jackal');
insert into petshop (name, age, kind) values ('Dalton', 55, 'Common waterbuck');
insert into petshop (name, age, kind) values ('Susanetta', 8, 'Swan, black');
insert into petshop (name, age, kind) values ('Allison', 2, 'Corella, long-billed');
insert into petshop (name, age, kind) values ('Lavina', 65, 'Cuis');
insert into petshop (name, age, kind) values ('Horatius', 4, 'Owl, australian masked');
insert into petshop (name, age, kind) values ('Nady', 18, 'Squirrel, uinta ground');
insert into petshop (name, age, kind) values ('Robby', 41, 'Lemur, lesser mouse');
insert into petshop (name, age, kind) values ('Lorilee', 90, 'Squirrel, grey-footed');
insert into petshop (name, age, kind) values ('Mallorie', 64, 'Jackal, indian');
insert into petshop (name, age, kind) values ('Elli', 99, 'Wombat, southern hairy-nosed');
insert into petshop (name, age, kind) values ('Luz', 24, 'Yellow baboon');
insert into petshop (name, age, kind) values ('Mart', 64, 'Tapir, brazilian');
insert into petshop (name, age, kind) values ('Carlina', 4, 'Bear, polar');
insert into petshop (name, age, kind) values ('Quill', 59, 'Squirrel, thirteen-lined');
insert into petshop (name, age, kind) values ('Meridith', 68, 'Ibex');
insert into petshop (name, age, kind) values ('Annabella', 76, 'Ring-tailed gecko');
insert into petshop (name, age, kind) values ('Cyrus', 20, 'Snake, western patch-nosed');
insert into petshop (name, age, kind) values ('Kevin', 61, 'Tortoise, burmese brown mountain');
insert into petshop (name, age, kind) values ('Bradan', 32, 'Tortoise, burmese brown mountain');
insert into petshop (name, age, kind) values ('Mora', 35, 'Weaver, white-browed sparrow');
insert into petshop (name, age, kind) values ('Simonette', 85, 'King cormorant');
insert into petshop (name, age, kind) values ('Gardie', 33, 'Rhinoceros, black');
insert into petshop (name, age, kind) values ('Torrance', 32, 'Colobus, black and white');
insert into petshop (name, age, kind) values ('Carry', 13, 'Heron, little');
insert into petshop (name, age, kind) values ('Geordie', 24, 'Brown brocket');
insert into petshop (name, age, kind) values ('Loren', 79, 'White-tailed deer');
insert into petshop (name, age, kind) values ('Elsinore', 6, 'Mexican wolf');
insert into petshop (name, age, kind) values ('Bobette', 80, 'Large cormorant');
insert into petshop (name, age, kind) values ('Jacquenette', 11, 'Waterbuck, common');
insert into petshop (name, age, kind) values ('Cyndia', 64, 'Ground monitor (unidentified)');
insert into petshop (name, age, kind) values ('Lil', 24, 'Egyptian vulture');
insert into petshop (name, age, kind) values ('Coral', 37, 'Long-crested hawk eagle');
insert into petshop (name, age, kind) values ('Erminie', 75, 'Ringtail, common');
insert into petshop (name, age, kind) values ('Bank', 69, 'Cormorant, large');
insert into petshop (name, age, kind) values ('Louella', 53, 'House crow');
insert into petshop (name, age, kind) values ('Clifford', 44, 'White-browed sparrow weaver');
insert into petshop (name, age, kind) values ('Tome', 65, 'Orca');
insert into petshop (name, age, kind) values ('Dyan', 42, 'Brown hyena');
insert into petshop (name, age, kind) values ('Ivie', 17, 'White-headed vulture');
insert into petshop (name, age, kind) values ('Clyde', 99, 'Starling, greater blue-eared');
insert into petshop (name, age, kind) values ('Glori', 74, 'Tern, arctic');
insert into petshop (name, age, kind) values ('Vikki', 68, 'Common nighthawk');
insert into petshop (name, age, kind) values ('Suellen', 99, 'Thirteen-lined squirrel');
insert into petshop (name, age, kind) values ('Crosby', 74, 'Capuchin, black-capped');
insert into petshop (name, age, kind) values ('Dolf', 72, 'Magellanic penguin');
insert into petshop (name, age, kind) values ('Corabella', 64, 'Little heron');
insert into petshop (name, age, kind) values ('Wood', 59, 'Goose, cape barren');
insert into petshop (name, age, kind) values ('Zak', 17, 'Opossum, american virginia');
insert into petshop (name, age, kind) values ('Alika', 74, 'Cobra, egyptian');
insert into petshop (name, age, kind) values ('Ingrim', 39, 'Whale, long-finned pilot');
insert into petshop (name, age, kind) values ('Jedd', 34, 'Eleven-banded armadillo (unidentified)');
insert into petshop (name, age, kind) values ('Gui', 5, 'Arctic lemming');
insert into petshop (name, age, kind) values ('Saxon', 88, 'Chestnut weaver');
insert into petshop (name, age, kind) values ('Myrwyn', 25, 'Giraffe');
insert into petshop (name, age, kind) values ('Reggy', 88, 'Cardinal, red-capped');
insert into petshop (name, age, kind) values ('Ariadne', 54, 'Magistrate black colobus');
insert into petshop (name, age, kind) values ('Franzen', 20, 'Crow, american');
insert into petshop (name, age, kind) values ('Barbe', 34, 'Red-capped cardinal');
insert into petshop (name, age, kind) values ('Atalanta', 32, 'Stork, white-necked');
insert into petshop (name, age, kind) values ('Martina', 48, 'Red sheep');
insert into petshop (name, age, kind) values ('Shelby', 53, 'Albatross, galapagos');
insert into petshop (name, age, kind) values ('Retha', 23, 'Andean goose');
insert into petshop (name, age, kind) values ('Locke', 10, 'White-winged black tern');
insert into petshop (name, age, kind) values ('Magdaia', 5, 'Kinkajou');
insert into petshop (name, age, kind) values ('Stefano', 75, 'Western patch-nosed snake');
insert into petshop (name, age, kind) values ('Zorah', 26, 'White-tailed deer');
insert into petshop (name, age, kind) values ('Tally', 40, 'Jabiru stork');
insert into petshop (name, age, kind) values ('Jacques', 72, 'Crested porcupine');
insert into petshop (name, age, kind) values ('Quintina', 69, 'Heron, yellow-crowned night');
insert into petshop (name, age, kind) values ('Isacco', 69, 'White-rumped vulture');
insert into petshop (name, age, kind) values ('Alfie', 40, 'Stork, european');
insert into petshop (name, age, kind) values ('Aland', 4, 'Dove, emerald-spotted wood');
insert into petshop (name, age, kind) values ('Booth', 46, 'European badger');
insert into petshop (name, age, kind) values ('Jeno', 59, 'American crow');
insert into petshop (name, age, kind) values ('Simonne', 55, 'Blesbok');
insert into petshop (name, age, kind) values ('Antoni', 47, 'Black-tailed prairie dog');
insert into petshop (name, age, kind) values ('Kyla', 54, 'Lesser masked weaver');
insert into petshop (name, age, kind) values ('Hill', 40, 'Ring-necked pheasant');
insert into petshop (name, age, kind) values ('Antoni', 53, 'Civet cat');
insert into petshop (name, age, kind) values ('Broddy', 6, 'Kafue flats lechwe');
insert into petshop (name, age, kind) values ('Cherri', 10, 'Dragonfly, russian');
insert into petshop (name, age, kind) values ('Delcine', 91, 'Snowy sheathbill');
insert into petshop (name, age, kind) values ('Clemmy', 99, 'Lizard, desert spiny');
insert into petshop (name, age, kind) values ('Quintana', 4, 'Serval');
insert into petshop (name, age, kind) values ('Rebbecca', 60, 'American marten');
insert into petshop (name, age, kind) values ('David', 57, 'African fish eagle');
insert into petshop (name, age, kind) values ('Dorothy', 28, 'Greater flamingo');
insert into petshop (name, age, kind) values ('Delcine', 92, 'Red lava crab');
insert into petshop (name, age, kind) values ('Sibel', 3, 'Tasmanian devil');
insert into petshop (name, age, kind) values ('Kimberlyn', 5, 'Barbet, black-collared');
insert into petshop (name, age, kind) values ('Pansy', 12, 'Boa, emerald green tree');
insert into petshop (name, age, kind) values ('Faustina', 73, 'Water monitor');
insert into petshop (name, age, kind) values ('Wilhelmina', 9, 'Cape cobra');
insert into petshop (name, age, kind) values ('Ebba', 20, 'Blacksmith plover');
insert into petshop (name, age, kind) values ('Cordy', 90, 'Malagasy ground boa');
insert into petshop (name, age, kind) values ('Tobe', 54, 'Stork, painted');
insert into petshop (name, age, kind) values ('Elaine', 94, 'Gull, herring');
insert into petshop (name, age, kind) values ('Guillema', 82, 'White-lipped peccary');
insert into petshop (name, age, kind) values ('Chick', 8, 'Woylie');
insert into petshop (name, age, kind) values ('Izabel', 31, 'African lynx');
insert into petshop (name, age, kind) values ('Marta', 14, 'Chestnut weaver');
insert into petshop (name, age, kind) values ('Willabella', 25, 'Mule deer');
insert into petshop (name, age, kind) values ('Sampson', 71, 'Greater sage grouse');
insert into petshop (name, age, kind) values ('Irita', 97, 'Egyptian goose');
insert into petshop (name, age, kind) values ('Lannie', 88, 'Coke''s hartebeest');
insert into petshop (name, age, kind) values ('Bonita', 99, 'African black crake');
insert into petshop (name, age, kind) values ('Wilmar', 96, 'Roadrunner, greater');
insert into petshop (name, age, kind) values ('Ladonna', 41, 'Genet, common');
insert into petshop (name, age, kind) values ('Karmen', 26, 'Black spider monkey');
insert into petshop (name, age, kind) values ('Turner', 88, 'Pampa gray fox');
insert into petshop (name, age, kind) values ('Durward', 69, 'Hawk, galapagos');
insert into petshop (name, age, kind) values ('Waylan', 86, 'White-mantled colobus');
insert into petshop (name, age, kind) values ('Noll', 35, 'Cat, african wild');
insert into petshop (name, age, kind) values ('Frazier', 58, 'Buttermilk snake');
insert into petshop (name, age, kind) values ('Ina', 21, 'Crowned eagle');
insert into petshop (name, age, kind) values ('Diena', 3, 'Monkey, vervet');
insert into petshop (name, age, kind) values ('Yard', 97, 'Common grenadier');
insert into petshop (name, age, kind) values ('Rebecca', 74, 'Agama lizard (unidentified)');
insert into petshop (name, age, kind) values ('Becka', 88, 'Booby, masked');
insert into petshop (name, age, kind) values ('Blakeley', 51, 'Rhinoceros, black');
insert into petshop (name, age, kind) values ('Rhona', 40, 'Red brocket');
insert into petshop (name, age, kind) values ('Aurie', 12, 'Bird, bare-faced go away');
insert into petshop (name, age, kind) values ('Adrianne', 79, 'Langur, gray');
insert into petshop (name, age, kind) values ('Didi', 84, 'Turkey, australian brush');
insert into petshop (name, age, kind) values ('Godfree', 40, 'Crane, stanley');
insert into petshop (name, age, kind) values ('Betteann', 29, 'Lizard, goanna');
insert into petshop (name, age, kind) values ('Brody', 10, 'Pale white-eye');
insert into petshop (name, age, kind) values ('Ashbey', 84, 'Thirteen-lined squirrel');
insert into petshop (name, age, kind) values ('Cassondra', 86, 'Pintail, white-cheeked');
insert into petshop (name, age, kind) values ('Urbanus', 45, 'Goose, knob-nosed');
insert into petshop (name, age, kind) values ('Cornie', 49, 'White-rumped vulture');
insert into petshop (name, age, kind) values ('Carney', 79, 'Hawk, red-tailed');
insert into petshop (name, age, kind) values ('Jacinta', 81, 'Partridge, coqui');
insert into petshop (name, age, kind) values ('Welbie', 3, 'Fox, blue');
insert into petshop (name, age, kind) values ('Judah', 13, 'Colobus, magistrate black');
insert into petshop (name, age, kind) values ('Adriana', 15, 'White-browed sparrow weaver');
insert into petshop (name, age, kind) values ('Ulrick', 84, 'Cat, miner''s');
insert into petshop (name, age, kind) values ('Brockie', 57, 'Lizard, mexican beaded');
insert into petshop (name, age, kind) values ('Craggy', 20, 'Topi');
insert into petshop (name, age, kind) values ('Isabelle', 38, 'White-headed vulture');
insert into petshop (name, age, kind) values ('Johnna', 9, 'Stick insect');
insert into petshop (name, age, kind) values ('Theobald', 86, 'Shrike, southern white-crowned');
insert into petshop (name, age, kind) values ('Ricoriki', 16, 'Bald eagle');
insert into petshop (name, age, kind) values ('Aprilette', 88, 'Bear, polar');
insert into petshop (name, age, kind) values ('Sharai', 89, 'Silver-backed fox');
insert into petshop (name, age, kind) values ('Latisha', 84, 'Whale, long-finned pilot');
insert into petshop (name, age, kind) values ('Rem', 62, 'Booby, blue-footed');
insert into petshop (name, age, kind) values ('Conny', 54, 'Pied crow');
insert into petshop (name, age, kind) values ('Mollie', 76, 'Koala');
insert into petshop (name, age, kind) values ('Trudy', 59, 'Lourie, grey');
insert into petshop (name, age, kind) values ('Ivett', 16, 'Gecko (unidentified)');
insert into petshop (name, age, kind) values ('Glynda', 46, 'Eastern quoll');
insert into petshop (name, age, kind) values ('Dacie', 88, 'Buffalo, american');
insert into petshop (name, age, kind) values ('Rawley', 61, 'Red-billed toucan');
insert into petshop (name, age, kind) values ('Clarence', 93, 'Blue crane');
insert into petshop (name, age, kind) values ('Dyanne', 18, 'Tern, arctic');
insert into petshop (name, age, kind) values ('Sonya', 20, 'Asian false vampire bat');
insert into petshop (name, age, kind) values ('Perla', 41, 'Wolf spider');
insert into petshop (name, age, kind) values ('Talya', 80, 'Bunting, crested');
insert into petshop (name, age, kind) values ('Allard', 15, 'Hyena, striped');
insert into petshop (name, age, kind) values ('Gwyneth', 90, 'Killer whale');
insert into petshop (name, age, kind) values ('Duane', 23, 'Pied cormorant');
insert into petshop (name, age, kind) values ('Marti', 13, 'Tern, white-winged black');
insert into petshop (name, age, kind) values ('Colman', 63, 'White-winged black tern');
insert into petshop (name, age, kind) values ('Federica', 77, 'Great horned owl');
insert into petshop (name, age, kind) values ('Heath', 19, 'Southern hairy-nosed wombat');
insert into petshop (name, age, kind) values ('Krishna', 12, 'Pallas''s fish eagle');
insert into petshop (name, age, kind) values ('Coretta', 22, 'Tawny frogmouth');
insert into petshop (name, age, kind) values ('Kai', 26, 'African bush squirrel');
insert into petshop (name, age, kind) values ('Hinze', 57, 'Alligator, american');
insert into petshop (name, age, kind) values ('Dannye', 39, 'Dragon, netted rock');
insert into petshop (name, age, kind) values ('Marissa', 80, 'Flamingo, roseat');
insert into petshop (name, age, kind) values ('Willabella', 17, 'White-faced tree rat');
insert into petshop (name, age, kind) values ('Bridie', 21, 'Arctic ground squirrel');
insert into petshop (name, age, kind) values ('Gradey', 79, 'Common pheasant');
insert into petshop (name, age, kind) values ('Colet', 41, 'Roadrunner, greater');
insert into petshop (name, age, kind) values ('Susanna', 97, 'Hoopoe, eurasian');
insert into petshop (name, age, kind) values ('Emmaline', 18, 'Cat, native');
insert into petshop (name, age, kind) values ('Lillis', 60, 'Toucan, red-billed');
insert into petshop (name, age, kind) values ('Sandie', 75, 'Caiman, spectacled');
insert into petshop (name, age, kind) values ('Kary', 51, 'Bahama pintail');
insert into petshop (name, age, kind) values ('Tibold', 92, 'Egyptian viper');
insert into petshop (name, age, kind) values ('Bev', 7, 'Eastern boa constrictor');
insert into petshop (name, age, kind) values ('Ricca', 70, 'Argalis');
insert into petshop (name, age, kind) values ('Christan', 3, 'Drongo, fork-tailed');
insert into petshop (name, age, kind) values ('Maura', 68, 'Buffalo, wild water');
insert into petshop (name, age, kind) values ('Genia', 33, 'Laughing kookaburra');
insert into petshop (name, age, kind) values ('Leia', 53, 'Tortoise, radiated');
insert into petshop (name, age, kind) values ('Aylmer', 68, 'Seal, northern fur');
insert into petshop (name, age, kind) values ('Valina', 41, 'Southern right whale');
insert into petshop (name, age, kind) values ('Alida', 20, 'Owl, madagascar hawk');
insert into petshop (name, age, kind) values ('Artemus', 65, 'Beaver, eurasian');
insert into petshop (name, age, kind) values ('Marita', 21, 'Reindeer');
insert into petshop (name, age, kind) values ('Margery', 30, 'Tortoise, indian star');
insert into petshop (name, age, kind) values ('Melinda', 86, 'Owl, snowy');
insert into petshop (name, age, kind) values ('Bing', 70, 'Sparrow, house');
insert into petshop (name, age, kind) values ('Marthena', 7, 'Hyena, brown');
insert into petshop (name, age, kind) values ('Ozzy', 28, 'Cat, kaffir');
insert into petshop (name, age, kind) values ('Jere', 69, 'Sifaka, verreaux''s');
insert into petshop (name, age, kind) values ('Luke', 28, 'Cape white-eye');
insert into petshop (name, age, kind) values ('Karen', 38, 'White-tailed jackrabbit');
insert into petshop (name, age, kind) values ('Lonnie', 83, 'Ibis, glossy');
insert into petshop (name, age, kind) values ('Warde', 69, 'Baboon, savanna');
insert into petshop (name, age, kind) values ('Israel', 61, 'Cape white-eye');
insert into petshop (name, age, kind) values ('Mariya', 2, 'Eland, common');
insert into petshop (name, age, kind) values ('Daron', 38, 'Coatimundi, white-nosed');
insert into petshop (name, age, kind) values ('Emmy', 39, 'Bee-eater, nubian');
insert into petshop (name, age, kind) values ('Chloe', 10, 'Crested screamer');
insert into petshop (name, age, kind) values ('Kiley', 77, 'Vulture, griffon');
insert into petshop (name, age, kind) values ('Carlotta', 18, 'Rattlesnake, dusky');
insert into petshop (name, age, kind) values ('Hillie', 99, 'Little heron');
insert into petshop (name, age, kind) values ('Doroteya', 25, 'Ox, musk');
insert into petshop (name, age, kind) values ('Flss', 37, 'Paddy heron (unidentified)');
insert into petshop (name, age, kind) values ('Kris', 29, 'Goose, cape barren');
insert into petshop (name, age, kind) values ('Flore', 29, 'Cape white-eye');
insert into petshop (name, age, kind) values ('Linnell', 72, 'European red squirrel');
insert into petshop (name, age, kind) values ('Patrica', 18, 'Laughing dove');
insert into petshop (name, age, kind) values ('Ringo', 1, 'Gull, silver');
insert into petshop (name, age, kind) values ('Zuzana', 72, 'Golden eagle');
insert into petshop (name, age, kind) values ('Leanor', 84, 'Ring-necked pheasant');
insert into petshop (name, age, kind) values ('Adara', 56, 'Coke''s hartebeest');
insert into petshop (name, age, kind) values ('Bone', 70, 'Nyala');
insert into petshop (name, age, kind) values ('Raleigh', 12, 'Bird, secretary');
insert into petshop (name, age, kind) values ('Kahaleel', 53, 'Possum, ring-tailed');
insert into petshop (name, age, kind) values ('Linea', 31, 'Lesser mouse lemur');
insert into petshop (name, age, kind) values ('Darleen', 24, 'Sarus crane');
insert into petshop (name, age, kind) values ('Debby', 82, 'Pied butcher bird');
insert into petshop (name, age, kind) values ('Lettie', 19, 'Rock dove');
insert into petshop (name, age, kind) values ('Nichole', 68, 'Rufous tree pie');
insert into petshop (name, age, kind) values ('Danila', 27, 'Large cormorant');
insert into petshop (name, age, kind) values ('Korey', 26, 'Otter, brazilian');
insert into petshop (name, age, kind) values ('Ramsay', 17, 'Crab-eating fox');
insert into petshop (name, age, kind) values ('Emogene', 34, 'Mara');
insert into petshop (name, age, kind) values ('Mala', 69, 'Brown hyena');
insert into petshop (name, age, kind) values ('Bucky', 91, 'Blue crane');
insert into petshop (name, age, kind) values ('Martica', 35, 'American marten');
insert into petshop (name, age, kind) values ('Shaina', 3, 'Indian star tortoise');
insert into petshop (name, age, kind) values ('Tucky', 65, 'Cormorant, pied');
insert into petshop (name, age, kind) values ('Alie', 58, 'Malabar squirrel');
insert into petshop (name, age, kind) values ('Malena', 51, 'Australian brush turkey');
insert into petshop (name, age, kind) values ('Issie', 5, 'Marabou stork');
insert into petshop (name, age, kind) values ('Nevin', 59, 'African ground squirrel (unidentified)');
insert into petshop (name, age, kind) values ('Germaine', 82, 'Harbor seal');
insert into petshop (name, age, kind) values ('Ivonne', 5, 'Eastern fox squirrel');
insert into petshop (name, age, kind) values ('Isidro', 25, 'Macaque, bonnet');
insert into petshop (name, age, kind) values ('Raff', 50, 'Pelican, australian');
insert into petshop (name, age, kind) values ('Maryann', 46, 'Huron');
insert into petshop (name, age, kind) values ('Rudd', 1, 'Woylie');
insert into petshop (name, age, kind) values ('Alissa', 43, 'Dog, bush');
insert into petshop (name, age, kind) values ('Ransom', 46, 'African fish eagle');
insert into petshop (name, age, kind) values ('Maurine', 77, 'Bushpig');
insert into petshop (name, age, kind) values ('Geneva', 87, 'Gazelle, grant''s');
insert into petshop (name, age, kind) values ('Lyndsay', 58, 'Hare, arctic');
insert into petshop (name, age, kind) values ('Rockey', 91, 'Herring gull');
insert into petshop (name, age, kind) values ('Pinchas', 44, 'Weeper capuchin');
insert into petshop (name, age, kind) values ('Kevyn', 9, 'Galapagos mockingbird');
insert into petshop (name, age, kind) values ('Kendricks', 73, 'Otter, small-clawed');
insert into petshop (name, age, kind) values ('Joan', 22, 'Crested bunting');
insert into petshop (name, age, kind) values ('Delmor', 57, 'Spider, wolf');
insert into petshop (name, age, kind) values ('Rosanne', 60, 'Cockatoo, slender-billed');
insert into petshop (name, age, kind) values ('Fayette', 42, 'Weaver, chestnut');
insert into petshop (name, age, kind) values ('Jania', 17, 'Sun gazer');
insert into petshop (name, age, kind) values ('Beverlee', 41, 'Southern elephant seal');
insert into petshop (name, age, kind) values ('Donica', 99, 'South African hedgehog');
insert into petshop (name, age, kind) values ('Evey', 66, 'Devil, tasmanian');
insert into petshop (name, age, kind) values ('Rochester', 4, 'Giant anteater');
insert into petshop (name, age, kind) values ('Corbin', 2, 'Cuis');
insert into petshop (name, age, kind) values ('Rebecca', 62, 'Mandras tree shrew');
insert into petshop (name, age, kind) values ('Denise', 8, 'Eagle, golden');
insert into petshop (name, age, kind) values ('Auberon', 20, 'Common raccoon');
insert into petshop (name, age, kind) values ('Joanie', 70, 'Common duiker');
insert into petshop (name, age, kind) values ('Charlene', 64, 'Cormorant, flightless');
insert into petshop (name, age, kind) values ('Gaylor', 47, 'Crested bunting');
insert into petshop (name, age, kind) values ('Reeba', 31, 'Phalarope, red-necked');
insert into petshop (name, age, kind) values ('Nan', 55, 'Flamingo, roseat');
insert into petshop (name, age, kind) values ('Natty', 91, 'Fairy penguin');
insert into petshop (name, age, kind) values ('Ninnetta', 53, 'Beaver, american');
insert into petshop (name, age, kind) values ('Lynnea', 69, 'Hawk, galapagos');
insert into petshop (name, age, kind) values ('Avie', 38, 'Golden-mantled ground squirrel');
insert into petshop (name, age, kind) values ('Eda', 79, 'Sunbird, lesser double-collared');
insert into petshop (name, age, kind) values ('Reinhard', 46, 'Three-banded plover');
insert into petshop (name, age, kind) values ('Rosana', 65, 'Black-crowned crane');
insert into petshop (name, age, kind) values ('Drusy', 97, 'Australian masked owl');
insert into petshop (name, age, kind) values ('Grazia', 45, 'Swan, trumpeter');
insert into petshop (name, age, kind) values ('Emmy', 41, 'Fairy penguin');
insert into petshop (name, age, kind) values ('Prudence', 99, 'Glossy starling (unidentified)');
insert into petshop (name, age, kind) values ('Ariel', 77, 'Cat, kaffir');
insert into petshop (name, age, kind) values ('Fanechka', 3, 'Clark''s nutcracker');
insert into petshop (name, age, kind) values ('Hermann', 70, 'Chacma baboon');
insert into petshop (name, age, kind) values ('Farra', 7, 'American marten');
insert into petshop (name, age, kind) values ('Yolanda', 70, 'White spoonbill');
insert into petshop (name, age, kind) values ('Floria', 33, 'Gull, southern black-backed');
insert into petshop (name, age, kind) values ('Will', 26, 'Small-clawed otter');
insert into petshop (name, age, kind) values ('Eddy', 5, 'American racer');
insert into petshop (name, age, kind) values ('Gifford', 4, 'American alligator');
insert into petshop (name, age, kind) values ('Elisabetta', 81, 'Cat, tiger');
insert into petshop (name, age, kind) values ('Deva', 35, 'Wallaby, tammar');
insert into petshop (name, age, kind) values ('Barn', 1, 'Arctic lemming');
insert into petshop (name, age, kind) values ('Cornell', 80, 'South American puma');
insert into petshop (name, age, kind) values ('Emmet', 75, 'Northern phalarope');
insert into petshop (name, age, kind) values ('Aubrey', 74, 'Fox, asian red');
insert into petshop (name, age, kind) values ('Teddy', 53, 'Great kiskadee');
insert into petshop (name, age, kind) values ('Vail', 58, 'Gull, southern black-backed');
insert into petshop (name, age, kind) values ('Micheil', 38, 'Grenadier, common');
insert into petshop (name, age, kind) values ('Elwyn', 1, 'Cougar');
insert into petshop (name, age, kind) values ('Nissa', 23, 'Verreaux''s sifaka');
insert into petshop (name, age, kind) values ('Adrianne', 23, 'Cliffchat, mocking');
insert into petshop (name, age, kind) values ('Sigismund', 82, 'Admiral, indian red');
insert into petshop (name, age, kind) values ('Fern', 75, 'Stork, painted');
insert into petshop (name, age, kind) values ('Shanon', 7, 'Ground monitor (unidentified)');
insert into petshop (name, age, kind) values ('Cecilio', 14, 'Baboon, olive');
insert into petshop (name, age, kind) values ('Clarke', 47, 'Admiral, indian red');
insert into petshop (name, age, kind) values ('Felicle', 38, 'Flightless cormorant');
insert into petshop (name, age, kind) values ('Petronilla', 73, 'Squirrel, nelson ground');
insert into petshop (name, age, kind) values ('Roderigo', 51, 'Mouflon');
insert into petshop (name, age, kind) values ('Mirabel', 38, 'European red squirrel');
insert into petshop (name, age, kind) values ('Xenia', 49, 'Red-breasted nuthatch');
insert into petshop (name, age, kind) values ('Olimpia', 16, 'European badger');
insert into petshop (name, age, kind) values ('Charla', 88, 'Monitor, white-throated');
insert into petshop (name, age, kind) values ('Ebba', 13, 'Ring-necked pheasant');
insert into petshop (name, age, kind) values ('Lorelle', 93, 'Magpie, australian');
insert into petshop (name, age, kind) values ('Zondra', 93, 'Blue and yellow macaw');
insert into petshop (name, age, kind) values ('Alix', 74, 'Mallard');
insert into petshop (name, age, kind) values ('Charley', 35, 'Sociable weaver');
insert into petshop (name, age, kind) values ('Ginger', 18, 'Duiker, gray');
insert into petshop (name, age, kind) values ('Orelle', 59, 'Kangaroo, red');
insert into petshop (name, age, kind) values ('Donnie', 92, 'Eastern quoll');
insert into petshop (name, age, kind) values ('Bekki', 78, 'Brown antechinus');
insert into petshop (name, age, kind) values ('Christalle', 40, 'Lesser flamingo');
insert into petshop (name, age, kind) values ('Briny', 8, 'Butterfly (unidentified)');
insert into petshop (name, age, kind) values ('Bartholomeus', 14, 'Squirrel, thirteen-lined');
insert into petshop (name, age, kind) values ('Lucius', 76, 'Sidewinder');
insert into petshop (name, age, kind) values ('Caritta', 70, 'Snowy egret');
insert into petshop (name, age, kind) values ('Yance', 86, 'Lion, south american sea');
insert into petshop (name, age, kind) values ('Gert', 95, 'Rhea, common');
insert into petshop (name, age, kind) values ('Ange', 53, 'Red-headed woodpecker');
insert into petshop (name, age, kind) values ('Aimil', 15, 'Burmese black mountain tortoise');
insert into petshop (name, age, kind) values ('Basilius', 14, 'Lion, australian sea');
insert into petshop (name, age, kind) values ('Mandy', 69, 'Monkey, red howler');
insert into petshop (name, age, kind) values ('Harald', 53, 'Crab (unidentified)');
insert into petshop (name, age, kind) values ('Wilek', 78, 'Reedbuck, bohor');
insert into petshop (name, age, kind) values ('Fae', 39, 'Turtle (unidentified)');
insert into petshop (name, age, kind) values ('Travers', 51, 'Red-knobbed coot');
insert into petshop (name, age, kind) values ('Heinrik', 75, 'Sloth, hoffman''s');
insert into petshop (name, age, kind) values ('Tamarra', 64, 'Tropical buckeye butterfly');
insert into petshop (name, age, kind) values ('Gae', 20, 'Waterbuck, common');
insert into petshop (name, age, kind) values ('Maryanna', 9, 'Lory, rainbow');
insert into petshop (name, age, kind) values ('Letisha', 6, 'Coke''s hartebeest');
insert into petshop (name, age, kind) values ('Tully', 36, 'Japanese macaque');
insert into petshop (name, age, kind) values ('Dorris', 57, 'Shrike, common boubou');
insert into petshop (name, age, kind) values ('Adiana', 81, 'Langur, common');
insert into petshop (name, age, kind) values ('Gerianna', 24, 'Robin, kalahari scrub');
insert into petshop (name, age, kind) values ('Baxter', 24, 'Andean goose');
insert into petshop (name, age, kind) values ('Zechariah', 55, 'Baboon, savanna');
insert into petshop (name, age, kind) values ('Alvin', 65, 'Cape cobra');
insert into petshop (name, age, kind) values ('Alejandra', 83, 'Gull, herring');
insert into petshop (name, age, kind) values ('Carola', 43, 'Owl, burrowing');
insert into petshop (name, age, kind) values ('Jessica', 34, 'Pacific gull');
insert into petshop (name, age, kind) values ('Karissa', 33, 'Rat, arboral spiny');
insert into petshop (name, age, kind) values ('Renelle', 86, 'Common rhea');
insert into petshop (name, age, kind) values ('Findley', 37, 'Bontebok');
insert into petshop (name, age, kind) values ('Emery', 68, 'Brocket, red');
insert into petshop (name, age, kind) values ('Deva', 15, 'Tarantula, salmon pink bird eater');
insert into petshop (name, age, kind) values ('Arlana', 75, 'Ring-tailed coatimundi');
insert into petshop (name, age, kind) values ('Devi', 13, 'Wood pigeon');
insert into petshop (name, age, kind) values ('Leda', 87, 'Greylag goose');
insert into petshop (name, age, kind) values ('Orelle', 27, 'Elk, Wapiti');
insert into petshop (name, age, kind) values ('Bogey', 82, 'Ring-tailed possum');
insert into petshop (name, age, kind) values ('Gerianna', 8, 'Tayra');
insert into petshop (name, age, kind) values ('Lurette', 90, 'Canadian tiger swallowtail butterfly');
insert into petshop (name, age, kind) values ('Willi', 80, 'Common zorro');
insert into petshop (name, age, kind) values ('Haze', 87, 'Shark, blue');
insert into petshop (name, age, kind) values ('Thorn', 57, 'African darter');
insert into petshop (name, age, kind) values ('Erek', 47, 'Hornbill, leadbeateri''s ground');
insert into petshop (name, age, kind) values ('Claudia', 38, 'Skunk, western spotted');
insert into petshop (name, age, kind) values ('Tam', 65, 'Macaw, red and blue');
insert into petshop (name, age, kind) values ('Stafani', 84, 'Snowy sheathbill');
insert into petshop (name, age, kind) values ('Lombard', 83, 'Buffalo, american');
insert into petshop (name, age, kind) values ('Camila', 16, 'Ring-tailed coatimundi');
insert into petshop (name, age, kind) values ('Bent', 42, 'Desert tortoise');
insert into petshop (name, age, kind) values ('Moises', 60, 'Ring-tailed gecko');
insert into petshop (name, age, kind) values ('Roscoe', 22, 'Bear, polar');
insert into petshop (name, age, kind) values ('Georg', 48, 'Cook''s tree boa');
insert into petshop (name, age, kind) values ('Fielding', 100, 'Eagle, long-crested hawk');
insert into petshop (name, age, kind) values ('Curtis', 95, 'Rat, white-faced tree');
insert into petshop (name, age, kind) values ('Eleanore', 85, 'Penguin, galapagos');
insert into petshop (name, age, kind) values ('Leslie', 86, 'Mocking cliffchat');
insert into petshop (name, age, kind) values ('Urbain', 24, 'Bulbul, african red-eyed');
insert into petshop (name, age, kind) values ('Stillman', 86, 'Southern right whale');
insert into petshop (name, age, kind) values ('Kile', 25, 'Mongoose, small indian');
insert into petshop (name, age, kind) values ('Reeba', 80, 'Blue peacock');
insert into petshop (name, age, kind) values ('Edlin', 82, 'Lemur, ring-tailed');
insert into petshop (name, age, kind) values ('Esdras', 50, 'Grebe, little');
insert into petshop (name, age, kind) values ('Marguerite', 89, 'Screamer, southern');
insert into petshop (name, age, kind) values ('Caressa', 68, 'Eagle, tawny');
insert into petshop (name, age, kind) values ('Hubey', 80, 'Euro wallaby');
insert into petshop (name, age, kind) values ('Delphinia', 38, 'Snowy sheathbill');
insert into petshop (name, age, kind) values ('Duffy', 14, 'Otter, small-clawed');
insert into petshop (name, age, kind) values ('Guthrey', 77, 'Saddle-billed stork');
insert into petshop (name, age, kind) values ('Christalle', 17, 'Tiger cat');
insert into petshop (name, age, kind) values ('Kayle', 99, 'Striated heron');
insert into petshop (name, age, kind) values ('Daryle', 14, 'Snake, green vine');
insert into petshop (name, age, kind) values ('Dacy', 41, 'Cape starling');
insert into petshop (name, age, kind) values ('Margret', 49, 'Suricate');
insert into petshop (name, age, kind) values ('Patton', 91, 'Serval');
insert into petshop (name, age, kind) values ('Guthry', 6, 'Tortoise, burmese brown mountain');
insert into petshop (name, age, kind) values ('Magda', 23, 'Snowy egret');
insert into petshop (name, age, kind) values ('Henry', 68, 'Rat, white-faced tree');
insert into petshop (name, age, kind) values ('Jeniffer', 46, 'Collared peccary');
insert into petshop (name, age, kind) values ('Daniella', 96, 'Mocking cliffchat');
insert into petshop (name, age, kind) values ('Milka', 86, 'Common seal');
insert into petshop (name, age, kind) values ('Aguste', 94, 'African elephant');
insert into petshop (name, age, kind) values ('Marve', 40, 'Deer, swamp');
